version: '3.8'
services:
  customers-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: customers-user
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017
  customers-db-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: customers-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: "pwd123456!"
      ME_CONFIG_MONGODB_SERVER: customers-db
      ME_CONFIG_MONGODB_AUTH_PASSWORD: db
    depends_on:
      - customers-db
  customers:
    image: mzegarra/ms-customers:graphql-v1.1
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - 8080:8080
#    healthcheck:
#      test: [ "CMD", "curl", "-I", "http://localhost:8080/actuator/health" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10