apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
type: Opaque
data:
    username: "bXplZ2FycmFAZ21haWwuY29t"
    password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: configserver-jks 
type: Opaque
data:
    KEYSTORE_PWD: "WU9VX0tFWVNUT1JFX1BBU1NXT1JE"
    KEYSTORE_SECRET: "WU9VX0tFWVNUT1JFX1BBU1NXT1JE"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver-settings
data:
    GIT_URI: "https://github.com/mzegarras/ms-configuration.git"
    KEYSTORE_ALIAS: "YOU_CONFIG_SERVER_KEY"

     
    
    