apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/version: "1.0.0"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: configserver
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: configserver
        image: mzegarra/ms-configuration:graphql-v1.1
        imagePullPolicy: Always
        # readinessProbe:
        #     httpGet:
        #       path: /actuator/health
        #       port: 8888
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     timeoutSeconds: 10
        #     successThreshold: 1
        #     failureThreshold: 3 
        # livenessProbe:
        #     httpGet:
        #       path: /actuator/health
        #       port: 8888
        #     initialDelaySeconds: 60
        #     periodSeconds: 10
        #     timeoutSeconds: 10
        #     successThreshold: 1
        #     failureThreshold: 3
        # livenessProbe:
        #     exec:
        #       command:
        #       - /bin/sh
        #       - -c
        #       - pgrep -f java
        #     failureThreshold: 3
        #     periodSeconds: 10
        #     successThreshold: 1
        #     timeoutSeconds: 1            
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi #256Mi
        ports:
          - containerPort: 8888
        envFrom:
          - configMapRef:
              name: configserver-settings
        volumeMounts:
          - name: configserver-key
            mountPath: /config-server.jks
            subPath: config-server.jks
        env:
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: username
          - name: GIT_PWD
            valueFrom:
              secretKeyRef:
                name: git-credentials
                key: password
          - name: KEYSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: configserver-jks
                key: KEYSTORE_PWD
          - name: KEYSTORE_SECRET
            valueFrom:
              secretKeyRef:
                name: configserver-jks
                key: KEYSTORE_SECRET
      volumes:
        - name: configserver-key
          secret:
            secretName: configserver-key
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/version: "1.0.0"
  type: ClusterIP
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
    name: "ms-configurations"
    labels:
        app: "ms-configurations"
data:
    SERVER_CONFIG_ENABLED: "true"
    SERVER_CONFIG_URL: "http://configserver:8888"
    SERVER_CONFIG_FAIL_FAST: "true"
    INITIAL_INTERVAL: "3000"
    MULTIPLIER: "2.0"
    MAXINTERVAL: "30000"
    MAXATTEMPTS: "100"