apiVersion: v1
kind: Secret
metadata:
  name: mongo-customers-secret
type: Opaque
data:
  username: Y3VzdG9tZXJzLXVzZXI=
  password: cHdkMTIzNDU2IQ==
---
apiVersion: v1
kind: Service
metadata:
  name: ms-customers-db
  labels:
    app: ms-customers-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: tcp
  selector:
     app: ms-customers-db
  type: ClusterIP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customers-db
spec:
  selector:
    matchLabels:
      app: ms-customers-db
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-customers-db
    spec:
      containers:
        - name: ms-customers-db
          image: mongo
          imagePullPolicy: Always
          ports:
            - name: tcp-api
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-customers-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-customers-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: db              
          resources:
            limits:
              cpu: 350m
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - mongo --eval db.adminCommand\(\"ping\"\)
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15                       
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - mongo --eval db.adminCommand\(\"ping\"\)
            failureThreshold: 3
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15