apiVersion: v1
kind: Service
metadata:
  name: ms-customers
  labels:
    app: ms-customers
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ms-customers
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customers
spec:
  selector:
    matchLabels:
      app: ms-customers
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ms-customers     
    spec:
      containers:
        - name: ms-customers
          image: mzegarra/ms-customers:graphql-v1.1
          # readinessProbe:
          #    httpGet:
          #      path: /actuator/health
          #      port: 7071
          #    initialDelaySeconds: 20
          #    periodSeconds: 10
          #    timeoutSeconds: 10
          #    successThreshold: 1
          #    failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ms-configurations