apiVersion: v1
kind: Service
metadata:
  name: ms-accounts
  labels:
    app: ms-accounts
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ms-accounts
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-accounts
spec:
  selector:
    matchLabels:
      app: ms-accounts
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ms-accounts
        version: v1
    spec:
      containers:
        - name: ms-accounts
          image: mzegarra/ms-accounts:graphql-v1.1
          # readinessProbe:
          #    httpGet:
          #      path: /actuator/health
          #      port: 7070
          #    initialDelaySeconds: 30
          #    periodSeconds: 10
          #    timeoutSeconds: 10
          #    successThreshold: 1
          #    failureThreshold: 3
          # livenessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - pgrep -f java
          #   failureThreshold: 3
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi        
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ms-configurations