apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: graphql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  selector:
    matchLabels:
      app: graphql
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: mzegarra/ms-graphql:graphql-v1.1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 3000
          env:       
            - name: PORT
              value: '3000'
            - name: URL_API_ACCOUNT
              value: 'http://ms-accounts:8080/'
            - name: URL_API_CUSTOMER
              value: 'http://ms-customers:8080/'
            - name: REDIS_HOST
              value: 'ms-graphql-cache'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: 'password'              