apiVersion: v1
kind: Secret
metadata:
    name: ms-graphql-cache-credentials
type: Opaque
data:
    redis_password: "cGFzc3dvcmQ=" #password
---
apiVersion: v1
kind: Service
metadata:
  name: ms-graphql-cache
  labels:
    app: ms-graphql-cache
spec:
  ports:
    - name: ms-graphql-cache
      port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP
  selector:
    app: ms-graphql-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-graphql-cache
spec:
  selector:
    matchLabels:
      app: ms-graphql-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-graphql-cache  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: ms-graphql-cache
          image: redis:4-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(PASSWORD)"]
          ports:
            - containerPort: 6379
              name: tcp
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 256Mi #256Mi
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-graphql-cache-credentials
                  key: redis_password 
