version: '3.3'
services:
  ms-configuration:
    image: mzegarra/ms-configuration:graphql-v1.1
    ports:
      - 8888:8888
    volumes:
      - ./config-server.jks:/config-server.jks
    environment:
      GIT_URI: "https://github.com/mzegarras/ms-configuration.git"
      GIT_USER: "mzegarra"
      GIT_PWD: ""
      KEYSTORE_PWD: "YOU_KEYSTORE_PASSWORD"
      KEYSTORE_ALIAS: "YOU_CONFIG_SERVER_KEY"
      KEYSTORE_SECRET: "YOU_KEYSTORE_PASSWORD"
  ms-customers-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: customers-user
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: db
    # ports:
    #   - 27017:27017
  # customers-db-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: customers-user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "pwd123456!"
  #     ME_CONFIG_MONGODB_SERVER: customers-db
  #     ME_CONFIG_MONGODB_AUTH_PASSWORD: db
  #   depends_on:
  #     - customers-db
  ms-customers:
    image: mzegarra/ms-customers:graphql-v1.1
    ports:
      - 8081:8080
    environment:
      SERVER_CONFIG_ENABLED: "true"
      SERVER_CONFIG_URL: "http://ms-configuration:8888"
      SERVER_CONFIG_FAIL_FAST: "true"
      INITIAL_INTERVAL: 1000
      MULTIPLIER: 2.0
      MAXINTERVAL: 30000
      MAXATTEMPTS: 100
    depends_on:
      - ms-customers-db
      - ms-configuration
  ms-accounts-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: accounts-user
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: db
  ms-accounts:
    image: mzegarra/ms-accounts:graphql-v1.1
    ports:
      - 8082:8080
    environment:
      SERVER_CONFIG_ENABLED: "true"
      SERVER_CONFIG_URL: "http://ms-configuration:8888"
      SERVER_CONFIG_FAIL_FAST: "true"
      INITIAL_INTERVAL: 1000
      MULTIPLIER: 2.0
      MAXINTERVAL: 30000
      MAXATTEMPTS: 100
    depends_on:
      - ms-accounts-db
      - ms-configuration
  ms-graphql:
    image: mzegarra/ms-graphql:graphql-v1.1
    ports:
      - 3001:3000
    environment:
      PORT: 3000
      URL_API_ACCOUNT: 'http://ms-accounts:8080/'
      URL_API_CUSTOMER: 'http://ms-customers:8080/'
      REDIS_HOST: 'ms-graphql-cache'
      REDIS_PORT: 6379
      REDIS_PASSWORD: 'password'
    depends_on:
      - ms-customers
      - ms-accounts
      - ms-graphql-cache
  ms-graphql-cache:
      image: redis:4-alpine
      command: sh -c 'echo "requirepass password" | redis-server -' 