version: '3.8'
services:
  accounts-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: accounts-user
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017
  accounts-db-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: accounts-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: "pwd123456!"
      ME_CONFIG_MONGODB_SERVER: accounts-db
      ME_CONFIG_MONGODB_AUTH_PASSWORD: db
    depends_on:
      - accounts-db
  accounts:
    image: "mzegarra/ms-accounts:graphql-v1.1"
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - 8083:8080